### ISSUE TITLE
Use SSL for communication

### ISSUE THREAD

**Issue by wresuolc** [internetarchive/FirefoxNoMore404s#1]
This is a review comment from a few months ago, but just want to make sure it wasn't lost:

The add-on isn't using https for pinging web.archive.org.  Let's use SSL everywhere we can.

**Comment by rchrd2** [comment]
I agree. This was fixed yesterday.

**Comment by thomaslevesque** [comment]
> I agree. This was fixed yesterday.

Maybe it was broken again then, because it doesn't use HTTPS now. Can we reopen this issue?

**Comment by thomaslevesque** [comment]
Actually, it uses HTTPS to check the availability of the page on archive.org, but it displays an HTTP link. It should show an HTTPS link.
