### ISSUE TITLE
Drop down gets covered by page content, appears to be inheriting some page styling

### ISSUE THREAD

**Issue by johngruen** [internetarchive/FirefoxNoMore404s#12]
Saw this looking at examples: 

<img width="1667" alt="screen shot 2016-06-22 at 9 50 28 am" src="https://cloud.githubusercontent.com/assets/3323249/16258617/f15c4aa2-385e-11e6-92a1-4d8f3c3ce520.png">

from:
https://www.pinterest.com/SuburbanDixie/

**Comment by johngruen** [comment]
@rchrd2 hey, if you think this is fixed in 1.4.3, feel free to close!

**Comment by rchrd2** [comment]
There are actually some adjustments that can be made based on how it renders on this page. Need to set a high z-index. So let's leave this open. Let me know if you notice any other pages where it renders incorrectly. Thanks.
