### ISSUE TITLE
Add-on link should be #0996f8

### ISSUE THREAD

**Issue by johngruen** [internetarchive/FirefoxNoMore404s#13]
Link is currently set to `color: blue`, should be `color: #0996f8`

**Comment by rchrd2** [comment]
Hi John,
Not sure if these issues are all related to the Pinterest page, but a few of them seem like things that have already been addressed. Is there a chance you tested with an outdated version?

At the time of writing, the latest version is 1.4.2. See attached file. [Wayback_Machine_Firefox_V1.4.2.xpi.zip](https://github.com/internetarchive/FirefoxNoMore404s/files/328437/Wayback_Machine_Firefox_V1.4.2.xpi.zip)

Also, we are currently debugging an issue that makes us no longer be able to install the addon after we upgraded Firefox. Would you mind trying this latest file and let me know if you can install it and if there are still css problems?

Thanks.

**Comment by pdehaan** [comment]
@rchrd2 Does the add-on auto-update when there is a newer version, or do I need to uninstall/reinstall to get the latest version?

**Comment by rchrd2** [comment]
It does not auto-upgrade when you install the development version with "Install Add-on from file".

We are working to publish this addon into the marketplace which may make it auto-update.

**Comment by johngruen** [comment]
FIxed in 1.4.3.
