### ISSUE TITLE
A couple errors when using `npm run build_unsigned`

### ISSUE THREAD

**Issue by pdehaan** [internetarchive/FirefoxNoMore404s#22]
Currently it looks like I get errors the first time I run `$ npm run build_unsigned` because the `./build_unsigned/` directory does not exist:

```sh
$ npm run build_unsigned

> FirefoxNoMore404s@1.4.3 build_unsigned /Users/pdehaan/dev/github/FirefoxNoMore404s
> mkdir build_unsigned && rm ./build_unsigned/*.zip && web-ext build --source-dir=src --artifacts-dir=build_unsigned

rm: ./build_unsigned/*.zip: No such file or directory

$ echo $? # 1
```

After running once, the directory is automatically created, and then running `$ npm run build_unsigned` fails again with a different error, because now `mkdir` fails:

```sh
$ npm run build_unsigned

> FirefoxNoMore404s@1.4.3 build_unsigned /Users/pdehaan/dev/github/FirefoxNoMore404s
> mkdir build_unsigned && rm ./build_unsigned/*.zip && web-ext build --source-dir=src --artifacts-dir=build_unsigned

mkdir: build_unsigned: File exists

$ echo $? # 1
```

I was able to hack it together locally by adding a `-p` flag to `mkdir` and a risky `-f` flag to `rm`:

```js
"build_unsigned": "mkdir -p build_unsigned && rm -f ./build_unsigned/*.zip && web-ext build --source-dir=src --artifacts-dir=build_unsigned",
```

Now it looks like I can build multiple times in a row without any blocking errors:

```sh
$ npm run build_unsigned

> FirefoxNoMore404s@1.4.3 build_unsigned /Users/pdehaan/dev/github/FirefoxNoMore404s
> mkdir -p build_unsigned && rm -f ./build_unsigned/*.zip && web-ext build --source-dir=src --artifacts-dir=build_unsigned

Building web extension from /Users/pdehaan/dev/github/FirefoxNoMore404s/src
Your web extension is ready: build_unsigned/no_more_404s-1.4.4.zip
```

We may also be reverse the order of the commands to do:

1. `rm -f ./build_unsigned` &mdash; force delete entire folder, whether it exists or not.
1. `mkdir build_unsigned` &mdash; recreate an empty artifact directory (since we're probably guaranteed that it won't exist after our terrifying `rm -f` in step 1).
1. `web-ext build --source-dir=src --artifacts-dir=build_unsigned` &mdash; go ahead and recreate the web extension in our empty artifact directory.

---

Both `rm` and `mkdir` are probably pretty Unix/macOS specific, but I guess we could technically use something like [**rimraf**](http://npm.im/rimraf) and [**mkdirp**](http://npm.im/mkdirp) if we wanted to be a bit more Windows friendly (at the cost of adding two new devDependencies).

**Comment by rchrd2** [comment]
Yes. I noticed this to. I am building and signing a new version. I'll resolve these and get back to you.
