### ISSUE TITLE
Running `make sign` command returns errors

### ISSUE THREAD

**Issue by pdehaan** [internetarchive/FirefoxNoMore404s#23]
Currently running `$ make sign` throws the following error:

```sh
$ make sign
npm run sign -- --api-key="x" --api-secret="y"

> FirefoxNoMore404s@1.4.3 sign /Users/pdehaan/dev/github/FirefoxNoMore404s
> rm ./build/*.xpi && web-ext sign --verbose -s=src -a=build && git add *.xpi "--api-key=x" "--api-secret=y"

/Users/pdehaan/dev/github/FirefoxNoMore404s/node_modules/.bin/web-ext sign

Options:
  ...<snip/>

Missing required arguments: api-key, api-secret
```

Here's the current `make sign` command in the Makefile:
```makefile
sign:
	npm run sign -- --api-key=$(JWT_ISSUER) --api-secret=$(JWT_SECRET)
```

It's cleverly passing our `--api-key` and `--api-secret` to the `npm run sign` command (using that tricky extra `--` in the middle of the command). But it looks like those variables are never being sent along to our npm script.

Looking deeper, it looks like our `npm run sign` command looks like this:

```js
"sign": "rm ./build/*.xpi && web-ext sign --verbose -s=src -a=build && git add *.xpi",
```

But because `&& git add *.xpi` is our last command, it looks like it's the one receiving those "missing" `--api-key=x` and `--api-secret=y` arguments, as you can see in the `npm run` output above:

```sh
rm ./build/*.xpi && web-ext sign --verbose -s=src -a=build && git add *.xpi "--api-key=x" "--api-secret=y"
```

Looks like we can make this work by using a `postsign` npm script hook which will run after the `sign` script executes:

```js
"sign": "rm ./build/*.xpi && web-ext sign --verbose -s=src -a=build",
"postsign": "git add build/*.xpi",
```

And now we get closer, but I get similar errors where we're trying to run `rm ./build/*.xpi` on a directory where no .xpi files may exist, so we have to use `rm -f ./build/*.xpi`, and then investigate whether we actually get .xpi files or .zip files with the newer **web-ext**.
Unfortunately, I'm having troubles digging too much deeper since I don't have valid `--api-key` or `--api-secret` values in my local CREDENTIALS file.

**Comment by rchrd2** [comment]
Hi. Since signed the extension can only be done once per version, I couldn't test until the next release. I just made a new version and in the process got rid of the Makefile all together. Everything is in the package.json now. It reads the CREDENTIALS file.
