### ISSUE TITLE
Add QA Test Plan

### ISSUE THREAD

**Issue by pdehaan** [internetarchive/FirefoxNoMore404s#24]
We should probably add a basic QA test plan to this repo so the QA team can run through the steps and verify each release.

Specifically, do we have a list of known 404s that we can use to test the user interaction?

---

**UPDATE:**
- https://www.pinterest.com/SuburbanDixie/
- http://rchrd.net/using-polling-to-automatically-update-ember-models/

**Comment by wresuolc** [comment]
https://wiki.mozilla.org/QA/NoMore404s

Doesn't look like I have permissions to close this issue

**Comment by rchrd2** [comment]
Hmm. I'll get you added.
