### ISSUE TITLE
Don't inject unsanitized remote content in the add-on

### ISSUE THREAD

**Issue by wresuolc** [internetarchive/FirefoxNoMore404s#28]
It's generally frowned on to inject unsanitized remote content in add-ons (and completely banned on AMO).  No More 404s does it in two places:

https://github.com/internetarchive/FirefoxNoMore404s/blob/master/src/scripts/background.js#L19
https://github.com/internetarchive/FirefoxNoMore404s/blob/master/src/scripts/background.js#L22

All we're doing is getting a URL back from the Wayback Machine, right?  Is there a reason that's executing code?

**Comment by rchrd2** [comment]
At the time of writing the addon this was a solution I found. Let me know what you recommend, and I can change it to that. 

Perhaps we can define a function in client.js and trigger that function from background.js.

**Comment by Skalman** [comment]
`JSON.stringify('\u2028')` creates a string that won't parse as JavaScript (`\u2028` and `\u2029` are line terminators in JavaScript, but not in JSON).

Non-standard alternatives that would work in Firefox would be `uneval(myString)` [[1]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/uneval) or `myString.toSource()`[[2]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toSource). The only standard way I know, would be `JSON.stringify(myString).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')`.
