### ISSUE TITLE
The text is truncated in the No More 404s bar

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [internetarchive/FirefoxNoMore404s#35]
![characters_cut_off](https://cloud.githubusercontent.com/assets/20083658/17403212/71adec5c-5a5f-11e6-84c3-f6b67f67340d.gif)
[Affected versions]:
    - Firefox 45 and up.
    - No More 404s 1.5.3

[Affected Platforms]:
    - All Linux.
    - All Windows.
    - All Mac OS.

[Prerequisites]:
    - Latest No More 404s add-on (1.5.3) is installed.

[Steps to reproduce]:
    1. Navigate to a website that is no longer available (eg. http://spartan.ac.brocku.ca/~lward/Dewey/Dewey_1903.html).
    2. Observe how the text in the No More 404s bar is displayed.

[Expected result]:
The text is correctly displayed.

[Actual result]:
Some characters like "g" and "y" are not fully visible, the lower part of the letters is truncated.

[Notes]:
    - We observed that scroll action can be done in the No More 404s notification bar in order to display the whole text. From our point of view, the scroll action should be disabled and the text should be fully displayed.
    - Attached a screen recording of the issue.

**Comment by sivaraam** [comment]
@SoftVision-EmilPasca I guess this is no longer an issue as the way the message is displayed has been changed.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (1.7.0).
