### ISSUE TITLE
https://play.rust-lang.org/ incorrectly detected as missing

### ISSUE THREAD

**Issue by jrmuizel** [internetarchive/FirefoxNoMore404s#37]
STR: Load https://play.rust-lang.org/ and the "This page appears to be missing drop down appears"

**Comment by markjohngraham** [comment]
Hmmm... the first resource requested via the URL responds with a 404.  

See attached. 
![pastedgraphic-14](https://cloud.githubusercontent.com/assets/15734192/17466701/9ebc2c2e-5cc9-11e6-9f83-6f022e6be0da.png)

**Comment by rchrd2** [comment]
Yes, there's nothing we can really do here. That page is returning a 404. Going to have to file as an edge case.
