### ISSUE TITLE
Disable No More 404 when the address is localhost

### ISSUE THREAD

**Issue by brwolfgang** [internetarchive/FirefoxNoMore404s#38]
Hi there, I work as a web developer and often test a website on localhost (or 127.0.0.1).
Sometimes I get a 404 error and bing! NM404 suggests to visit the web archive.

I believe this behavior is inadequate and should be fixed.

**Comment by rchrd2** [comment]
Hello. This is a good point. I'll make sure to add this to the extension.

**Comment by rchrd2** [comment]
Closed with https://github.com/internetarchive/FirefoxNoMore404s/commit/d1acffcebf04679b164488998fc5c67738cc9a28
