### ISSUE TITLE
strict_min_version is 45.0

### ISSUE THREAD

**Issue by wresuolc** [internetarchive/FirefoxNoMore404s#39]
In the manifest we install on anything over version 45:  https://github.com/internetarchive/FirefoxNoMore404s/blob/master/src/manifest.json#L14

But I think we said this add-on doesn't work unless the user is using 48?  Shouldn't this be 48 then?

/cc @ckprice @johngruen

**Comment by rchrd2** [comment]
I am not sure if it's this extension that needs 48, or if it's the test pilot extension. I'll raise this one to 48 anyway just in case.

**Comment by wresuolc** [comment]
It's for webextensions.  They are considered stable in 48, and I heard this one didn't work in <48, but was looking for confirmation. :)  If you want to just change it, that works.  I can push that out today if you land it.

**Comment by rchrd2** [comment]
It looks like I have been using 47.0.1 on a Mac this whole time so it definitely doesn't require 48. I can change it to 48 for good measure if that's what is considered stable.

I am also working on a few other updates right now. Will push a new version soon.

**Comment by wresuolc** [comment]
Ok. I can wait on 1.5.4 and you can roll everything into it?

**Comment by rchrd2** [comment]
I don't think the tooling allows building and signing the same version. Last time I tried, it gives an error when I try to rebuild without bumbing the version. The next version will be 1.5.5.

**Comment by wresuolc** [comment]
Ok.  I'll release 1.5.4 as is then, and no rush on 1.5.5.  Cheers

**Comment by rchrd2** [comment]
Sounds good.

Closed with https://github.com/internetarchive/FirefoxNoMore404s/commit/b8e6fcac03af210784cc157ea1d109b70b875a69

Just pushed v1.5.5
