### ISSUE TITLE
Use RegExp+destructuring to parse dates?

### ISSUE THREAD

**Issue by pdehaan** [internetarchive/FirefoxNoMore404s#4]
In [./src/scripts/client.js:7-22](https://github.com/internetarchive/FirefoxNoMore404s/blob/e50b313ab6cee2c7702ae524b9828281df3d8a34/src/scripts/client.js#L7-L22) we parse dates using `.substring()`, and then join the strings back together with concatenation.

Not sure if it'd be easier or more flexible to use RegExp and some ES6 destructuring (verified this worked in 46.0.1), but it also creates a Date object (assuming UTC timestamp) and we can probably do better locale-specific formatting.

This also does a bit of extra validation to make sure we're receiving exactly 4+2+2 + 2+2+2 digits, and not letters or unexpected characters.

```js
function convertFromTimestamp(timestamp) {
  const timestampRE = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/;
  const matches = timestamp.match(timestampRE);

  if (!matches) {
    console.error("Invalid timestamp");
    return timestamp;
  }

  const [, yyyy, mm, dd, h, m, s] = matches;
  const utcDate = new Date(Date.UTC(yyyy, mm - 1 /* zero indexed */, dd, h, m, s));
  return utcDate.toLocaleString();

  // console.log("toString:\t", utcDate.toString());
  // console.log("toDateString:\t", utcDate.toDateString());
  // console.log("toTimeString:\t", utcDate.toTimeString());

  // console.log("toLocaleString:\t", utcDate.toLocaleString());
  // console.log("toLocaleDateString:\t", utcDate.toLocaleDateString());
  // console.log("toLocaleTimeString:\t", utcDate.toLocaleTimeString());
}


console.log(convertFromTimestamp("20160127182151")); // 1/27/2016, 10:21:51 AM
/*
toString:	 Wed Jan 27 2016 10:21:51 GMT-0800 (PST)
toDateString:	 Wed Jan 27 2016
toTimeString:	 10:21:51 GMT-0800 (PST)

toLocaleString:	 1/27/2016, 10:21:51 AM
toLocaleDateString:	 1/27/2016
toLocaleTimeString:	 10:21:51 AM
*/
```

**Comment by rchrd2** [comment]
Thanks for this great feedback. Being unsure of when ES6 was added, I used basic es5. I also found `toLocaleDateString`, which is preferred. Here's what I ended up with:
```
  function convertFromTimestamp(timestamp) {
    var timestampRE = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/;
    var matches = matches = timestamp.match(timestampRE);
    if (!matches) {
      console.error("Invalid timestamp");
      return timestamp;
    }
    var utcDate = new Date(Date.UTC(
      matches[1],
      matches[2] - 1 /* zero indexed */,
      matches[3],
      matches[4],
      matches[5],
      matches[6]
    ));
    var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    return utcDate.toLocaleDateString(undefined, options);
  }
```
Will push this change now. Let me know if you notice anything wrong. Thanks, again!

**Comment by rchrd2** [comment]
Now that I'm testing this, I wonder if translation is the way to go. For example, we end up with half spanish and english:
```
Visit the site as it was captured on viernes, 13 de noviembre de 2015
```

**Comment by rchrd2** [comment]
Okay, @pdehaan your original idea was better. Going to use `toLocaleString` instead.
