### ISSUE TITLE
Implement Styles to Match UX Spec

### ISSUE THREAD

**Issue by johngruen** [internetarchive/FirefoxNoMore404s#5]
![wayback version one 2x](https://cloud.githubusercontent.com/assets/3323249/15689212/e7d83ec4-274b-11e6-8e4d-dbebaf2010ac.png)
[Wayback Version One.pdf](https://github.com/internetarchive/FirefoxNoMore404s/files/292072/Wayback.Version.One.pdf)

You can copy and paste from the PDF

**Comment by johngruen** [comment]
Here's a link to the close SVG: https://www.dropbox.com/s/0d539agcasms4s3/Close.svg?dl=0

**Comment by rchrd2** [comment]
Hello. Thanks for these suggestions. I have updated the styles and text template to match your pdf.

One note: I did not change the height to be 50px, because in small width windows, this caused a problem. The latest version (atm) is v1.3.1.

**Comment by rchrd2** [comment]
Oh, I am also working on getting an SVG asset. Once I have that I will update the plugin. Should be soon.

**Comment by rchrd2** [comment]
Hello again. The plugin now uses an SVG, and also I updated the font to be "14px message-box".  I believe that takes care of everything in this ticket. Here's a screenshot. Let me know if you think this is resolved.
 
![screen shot 2016-06-01 at 18 07 25](https://cloud.githubusercontent.com/assets/182479/15730730/fbc5b654-2823-11e6-996b-92bcc026f310.png)

**Comment by johngruen** [comment]
hey @rchrd2 look good to me...two little changes

1. The `message-box` font can't be set on a `font-family` property, it has to be set on a `font` property. The rule comes from some internal Firefox style sheet magic. It should default to a sans-serif.
2. Make the box shadow on the big div:  `box-shadow: 0 0 10px rgba(0, 0, 0, 0.4), 0 1px 0 rgba(0, 0, 0, 0.3);`

**Comment by rchrd2** [comment]
@johngruen I'll make the box-shadow change. However, the font is already set using the font property. It's essentially set like this:

```
el.style.font = "14px message-box";
```

Does it not look correct? Could it be a problem with it being set on the element's style attribute instead of through a css file?

**Comment by johngruen** [comment]
@rchrd2 Yeah, that might be it. I'll have to chase down what the Font stack should be in CSS. Probably best to go ahead and merge in these changes and I can file a follow on bug. Thanks!

**Comment by rchrd2** [comment]
@johngruen Okay let me know if you find out any more info about making `message-box` work with inline styles. In the meantime, I set it to `14px message-box, sans-serif` and it looks more like your example pdf. Here's the source if you're interested: https://github.com/internetarchive/FirefoxNoMore404s/blob/master/src/scripts/client.js#L69
