### ISSUE TITLE
NoMore404s bar isn't displayed on latest Nightly

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [internetarchive/FirefoxNoMore404s#61]
[Affected versions]:
- Nightly 53.0a1-20161115030213
- NoMore404s 1.6.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest NoMore404s add-on (v1.6.0) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Navigate to a website that is no longer available (eg. http://spartan.ac.brocku.ca/~lward/Dewey/Dewey_1903.html).
2. Observe if NoMore404s bar is displayed.

[Expected result]:
- The archived page from Wayback Machine is offered in the NoMore404s bar.

[Actual result]:
- The NoMore404s bar isn't displayed.

[Notes]:
- Performed a regression, below are the results:
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=60266cddf76a3c6d34266b64ad63d835d48ceb76&tochange=3e357271c0f733762d9cc5f5c70112b655e07a1e

Looks like the following bug has the changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1273138

**Comment by johngruen** [comment]
This should be resolved here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1318800

**Comment by johngruen** [comment]
appears there's traction on this issue now

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Nightly (53.0a1-20161201030205).

**Comment by SoftVision-EmilPasca** [comment]
The issue is now reproducible on the latest Developer Edition (52.0a2-20161205004004).

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (1.7.0).
